server:
 port: 8080
 servlet:
  context-path: /

spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/wechat?serverTimezone=Asia/Shanghai
  username: root
  password: 123456

mybatis-plus:
 global-config:
  db-config:
   id-type: auto #id生成规则：数据库id自增
 configuration:
  map-underscore-to-camel-case: false # 开启驼峰功能
  auto-mapping-behavior: full # 自动映射任何复杂的结果
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 mapper-locations: classpath:/mapper/*.xml

wexin:
 jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
 appid: wxfa5befdb457bcbf5
 secret: 99e382f756189958a61d722c78bed096

bigTypeImagesFilePath: F://competition/project/wx/bigTypeImgs/
productImagesFilePath: F://competition/project/wx/productImgs/
swiperImagesFilePath: F://competition/project/wx/swiperImgs/
productSwiperImagesFilePath: F://competition/project/wx/productSwiperImgs/